import ts from "typescript"
import { describe, expect, it } from "vitest"
import { createMemoryHost } from "../../src/core/host.js"
import { createResolver, DEFAULT_CANDIDATE_SUFFIXES } from "../../src/core/resolver.js"
import { runDetection } from "../../src/detect/index.js"
import { DETECT_SCORE_LAST_RESORT } from "../../src/adapters/state-screens.js"
import type { ProjectProbeInput } from "../../src/detect/project.js"
import { createProjectProbe, manifestCandidates, parseNpmAlias } from "../../src/detect/project.js"

const ROOT = "/repo"

const PAGE = "export default () => null"

const probeOf = (
  files: Readonly<Record<string, string>>,
  options: { readonly symlinks?: readonly string[] } & Omit<ProjectProbeInput, "ts" | "root" | "host"> = {},
) => {
  const { symlinks, ...rest } = options
  return createProjectProbe({
    ts,
    root: ROOT,
    host: createMemoryHost({
      files: Object.fromEntries(Object.entries(files).map(([file, content]) => [`${ROOT}/${file}`, content])),
      ...(symlinks === undefined ? {} : { symlinks: symlinks.map((entry) => `${ROOT}/${entry}`) }),
    }),
    ...rest,
  })
}

const TSCONFIG = JSON.stringify({ compilerOptions: { baseUrl: "." }, include: ["src"] })

const PACKAGE = JSON.stringify({ name: "fixture", dependencies: { next: "15.0.0" } })

describe("directory exclusions", () => {
  const EXCLUDED_DIRS = [
    ".next",
    "dist",
    "build",
    "builds",
    ".output",
    "storybook-static",
    "coverage",
    "node_modules",
    ".vercel",
    "out",
    ".turbo",
    ".cache",
  ] as const

  it.each(EXCLUDED_DIRS)("never walks into %s/", (dir) => {
    const probe = probeOf({
      "tsconfig.json": TSCONFIG,
      "package.json": PACKAGE,
      "src/app/page.tsx": PAGE,
      [`${dir}/server/app/leaked/page.tsx`]: PAGE,
    })

    expect(probe.glob("**/app/**/page.tsx")).toEqual(["src/app/page.tsx"])
    expect(probe.scan().files.some((file) => file.startsWith(`${dir}/`))).toBe(false)
    expect(probe.scan().skippedDirs).toContain(dir)
  })

  it("does not report build output under .next/ as next pages", () => {
    const generatedPages = Object.fromEntries(
      Array.from({ length: 23 }, (_value, index) => [`.next/server/app/route-${String(index)}/page.js`, PAGE]),
    )
    const probe = probeOf({
      "tsconfig.json": TSCONFIG,
      "package.json": PACKAGE,
      "src/app/page.tsx": PAGE,
      ...generatedPages,
    })

    expect(probe.glob("**/app/**/page.{tsx,jsx,ts,js}")).toHaveLength(1)
  })

  it("an MV3 manifest under build output is never probed", () => {
    const mv3 = JSON.stringify({ manifest_version: 3, action: { default_popup: "p.html" } })
    const detection = runDetection({
      ts,
      root: ROOT,
      probe: probeOf({ "tsconfig.json": TSCONFIG, "package.json": PACKAGE, "dist/manifest.json": mv3 }),
    })

    // The bonus is what the exclusion denies; the always-applicable last resort of 1 remains.
    expect(detection.detections.find((entry) => entry.source === "state-screens")?.score).toBe(
      DETECT_SCORE_LAST_RESORT,
    )
  })

  it("keeps node_modules and .git excluded even when `exclude` is overridden", () => {
    const probe = probeOf(
      {
        "tsconfig.json": TSCONFIG,
        "package.json": PACKAGE,
        "src/a.ts": "export {}",
        "node_modules/pkg/index.ts": "export {}",
        "vendor/b.ts": "export {}",
      },
      { exclude: ["vendor"] },
    )

    expect(probe.glob("**/*.ts")).toEqual(["src/a.ts", "tsconfig.json"].filter((file) => file.endsWith(".ts")))
    expect(probe.excludedDirs).toContain("node_modules")
    expect(probe.excludedDirs).toContain(".git")
    expect(probe.excludedDirs).toContain("vendor")
  })
})

describe("generated files", () => {
  it("flags a *.gen.ts route tree by basename and keeps it out of probe files", () => {
    const probe = probeOf({
      "tsconfig.json": TSCONFIG,
      "package.json": PACKAGE,
      "src/routeTree.gen.ts": "// @ts-nocheck\n// generated by tanstack\nexport const routeTree = {}",
      "src/api.gen.ts": "export const api = {}",
      "src/routes/index.tsx": PAGE,
    })

    expect(probe.probeFiles()).toEqual(["src/routes/index.tsx"])
    expect(probe.generatedFiles()).toEqual([
      { file: "src/api.gen.ts", reason: "generated-basename" },
      { file: "src/routeTree.gen.ts", reason: "generated-marker" },
    ])
  })

  it("needs BOTH a directive and a generated marker to flag by content", () => {
    const probe = probeOf({
      "tsconfig.json": TSCONFIG,
      "package.json": PACKAGE,
      "src/both.ts": "// @ts-nocheck\n/* auto-generated — do not edit */\nexport const a = 1",
      "src/directive-only.ts": "// @ts-nocheck\nexport const b = 2",
      "src/marker-only.ts": "// generated at build time\nexport const c = 3",
    })

    expect(probe.generatedFiles()).toEqual([{ file: "src/both.ts", reason: "generated-marker" }])
    expect(probe.probeFiles()).toEqual(["src/directive-only.ts", "src/marker-only.ts"])
  })

  it("reports a config-glob generated file with that reason", () => {
    const probe = probeOf(
      { "tsconfig.json": TSCONFIG, "package.json": PACKAGE, "src/api-types.ts": "export type A = 1" },
      { generated: ["src/api-*.ts"] },
    )

    expect(probe.generatedFiles()).toEqual([{ file: "src/api-types.ts", reason: "config-glob" }])
  })
})

describe("symlinks", () => {
  it("records a symlink and never follows it", () => {
    const probe = probeOf(
      {
        "tsconfig.json": TSCONFIG,
        "package.json": PACKAGE,
        "src/a.ts": "export {}",
        "packages/linked/deep/b.ts": "export {}",
      },
      { symlinks: ["packages/linked"] },
    )

    expect(probe.scan().symlinks).toEqual(["packages/linked"])
    expect(probe.scan().files.some((file) => file.startsWith("packages/linked"))).toBe(false)
  })

  it("a workspace symlink outside node_modules cannot loop the walk", () => {
    const probe = probeOf(
      { "tsconfig.json": TSCONFIG, "package.json": PACKAGE, "src/a.ts": "export {}", "src/self/x.ts": "export {}" },
      { symlinks: ["src/self"] },
    )

    expect(probe.scan().files).toEqual(["package.json", "src/a.ts", "tsconfig.json"])
  })
})

describe("npm: alias specifiers", () => {
  it("reads dependency KEYS and never parses the value as semver", () => {
    const probe = probeOf({
      "tsconfig.json": TSCONFIG,
      "package.json": JSON.stringify({
        dependencies: { "react-router-dom": "^6.0.0" },
        devDependencies: { typescript: "npm:@typescript/typescript6@^6.0.2" },
      }),
    })

    expect(probe.context.hasDependency("typescript")).toBe(true)
    expect(probe.context.hasDependency("@typescript/typescript6")).toBe(false)
    expect(probe.dependencies.aliases).toEqual([
      {
        name: "typescript",
        manifest: "package.json",
        spec: "npm:@typescript/typescript6@^6.0.2",
        target: "@typescript/typescript6",
        range: "^6.0.2",
      },
    ])
  })

  it("splits the alias on the LAST @ so the scope survives", () => {
    expect(parseNpmAlias("npm:@typescript/typescript6@^6.0.2")).toEqual({
      target: "@typescript/typescript6",
      range: "^6.0.2",
    })
    expect(parseNpmAlias("npm:left-pad@1.0.0")).toEqual({ target: "left-pad", range: "1.0.0" })
    expect(parseNpmAlias("npm:left-pad")).toEqual({ target: "left-pad", range: "*" })
    expect(parseNpmAlias("^6.0.2")).toBeNull()
  })

  it("unions dependencies across the root and each source root's manifest", () => {
    const probe = probeOf({
      "tsconfig.json": JSON.stringify({ compilerOptions: { paths: { "@/*": ["frontend/src/*"] } } }),
      "package.json": JSON.stringify({ dependencies: { typescript: "npm:@typescript/typescript6@^6" } }),
      "frontend/package.json": JSON.stringify({ dependencies: { zustand: "5.0.0" } }),
      "frontend/src/a.ts": "export {}",
    })

    expect(manifestCandidates(["frontend/src"])).toEqual([
      "frontend/package.json",
      "frontend/src/package.json",
      "package.json",
    ])
    expect([...probe.dependencies.names].sort()).toEqual(["typescript", "zustand"])
  })

  it("ignores an unparseable manifest instead of throwing", () => {
    const probe = probeOf({ "tsconfig.json": TSCONFIG, "package.json": "{ not json" })
    expect(probe.dependencies.names.size).toBe(0)
  })
})

describe("derived source roots and kind rules", () => {
  it("derives roots from include, baseUrl and every paths target", () => {
    const probe = probeOf({
      "tsconfig.json": JSON.stringify({
        compilerOptions: { baseUrl: ".", paths: { "@/*": ["src/*"], "~app/*": ["app/*"] } },
        include: ["src", "app"],
      }),
      "package.json": PACKAGE,
      "src/a.ts": "export {}",
      "app/b.ts": "export {}",
    })

    expect(probe.derivedSourceRoots).toEqual(["app", "src"])
    expect(probe.paths.sourceRootsRel).toEqual(["app", "src"])
  })

  it("adds the root to the narrow roots when an include pattern starts with a wildcard", () => {
    const probe = probeOf({
      "tsconfig.json": JSON.stringify({
        compilerOptions: { baseUrl: ".", paths: { "@/ui/*": ["ui/*"], "@/lib/*": ["lib/*"] } },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", "../../packages/ui/src/hook.ts"],
      }),
      "package.json": PACKAGE,
      "app/page.tsx": PAGE,
      "ui/a.tsx": PAGE,
      "lib/b.ts": "export {}",
    })

    expect(probe.derivedSourceRoots).toEqual([".", "lib", "ui"])
  })

  it("falls back to the root when the tsconfig names nothing usable", () => {
    const probe = probeOf({
      "tsconfig.json": JSON.stringify({ compilerOptions: {} }),
      "package.json": PACKAGE,
      "a.ts": "export {}",
    })
    expect(probe.derivedSourceRoots).toEqual(["."])
  })

  it("keeps the vocabulary rules under a narrow root once a wildcard include adds the root", () => {
    const detection = runDetection({
      ts,
      root: ROOT,
      probe: probeOf({
        "tsconfig.json": JSON.stringify({
          compilerOptions: { baseUrl: ".", paths: { "~/*": ["./app/*"] } },
          include: ["**/*.ts", "**/*.tsx"],
        }),
        "package.json": PACKAGE,
        "app/routes/home.tsx": PAGE,
        "app/hooks/useOrders.ts": "export {}",
      }),
    })

    const prefixes = detection.kindRules.map((rule) => rule.match.pathPrefix)
    expect(prefixes).toContain("app/hooks/")
    expect(prefixes).toContain("hooks/")
  })

  it("reads paths through the extends chain and turns each alias into a kind rule", () => {
    const detection = runDetection({
      ts,
      root: ROOT,
      probe: probeOf({
        "tsconfig.base.json": JSON.stringify({
          compilerOptions: {
            baseUrl: ".",
            paths: { "@/modules/*": ["src/modules/*"], "@/shared/*": ["src/shared/*"] },
          },
        }),
        "tsconfig.json": JSON.stringify({ extends: "./tsconfig.base.json", include: ["src"] }),
        "package.json": PACKAGE,
        "src/modules/orders/OrdersPage.tsx": PAGE,
        "src/shared/helpers/paths.ts": "export {}",
      }),
    })

    expect(detection.tsconfig.files).toEqual(["tsconfig.base.json", "tsconfig.json"])
    expect(Object.keys(detection.tsconfig.paths)).toEqual(["@/modules/*", "@/shared/*"])

    const aliasRules = detection.kindRules.filter((rule) => rule.priority === 10)
    expect(aliasRules).toEqual([
      { match: { pathPrefix: "src/modules/" }, kind: "module", traversable: false, screenEntry: true, priority: 10 },
      { match: { pathPrefix: "src/shared/" }, kind: "shared", traversable: false, screenEntry: false, priority: 10 },
    ])
    expect(detection.kindRules[detection.kindRules.length - 1]).toEqual({
      match: {},
      kind: "other",
      traversable: false,
      screenEntry: false,
      priority: 0,
    })
  })

  it("reports a missing tsconfig as a diagnostic rather than throwing", () => {
    const detection = runDetection({ ts, root: ROOT, probe: probeOf({ "package.json": PACKAGE }) })
    expect(detection.diagnostics.map((entry) => entry.code)).toContain("project/no-tsconfig")
  })

  it("derives nodenext resolution options from the tsconfig", () => {
    const probe = probeOf({
      "tsconfig.json": JSON.stringify({ compilerOptions: { moduleResolution: "nodenext" }, include: ["src"] }),
      "package.json": PACKAGE,
      "src/a.ts": "export {}",
    })

    expect(probe.extensionRewrites.map((rewrite) => rewrite.from)).toEqual([".js", ".jsx", ".mjs"])
    expect(probe.candidateSuffixes).toContain("/index.ts")
  })
})

describe("determinism", () => {
  it("returns codepoint-sorted globs and a stable scan", () => {
    const probe = probeOf({
      "tsconfig.json": TSCONFIG,
      "package.json": PACKAGE,
      "src/b.ts": "export {}",
      "src/A.ts": "export {}",
      "src/a.ts": "export {}",
    })

    expect(probe.glob("src/*.ts")).toEqual(["src/A.ts", "src/a.ts", "src/b.ts"])
    expect(probe.glob("src/*.ts")).toEqual(probe.scan().files.filter((file) => /^src\/[^/]+\.ts$/.test(file)))
    expect(probe.globs().map((attempt) => attempt.matches)).toEqual([3, 3])
  })
})

describe("Vue single-file components in phase 0", () => {
  const files = {
    "tsconfig.json": TSCONFIG,
    "package.json": PACKAGE,
    "src/App.vue": '<template><div /></template>\n<script setup lang="ts">\nexport const links = { home: "/" }\n</script>\n',
    "src/main.ts": PAGE,
    "src/styles.css": ".a {}",
  }

  it("includes .vue files in probeFiles", () => {
    expect(probeOf(files).probeFiles()).toEqual(["src/App.vue", "src/main.ts"])
  })

  it("parses a .vue file through its virtual script", () => {
    const source = probeOf(files).parse("src/App.vue")
    expect(source?.statements).toHaveLength(1)
    expect(source?.getLineAndCharacterOfPosition(source.statements[0]?.getStart(source) ?? 0).line).toBe(2)
  })
})

describe("platform candidate suffixes", () => {
  const NATIVE_PACKAGE = JSON.stringify({ name: "fixture", dependencies: { "react-native": "0.76.0" } })

  const WEB_PACKAGE = JSON.stringify({ name: "fixture", dependencies: { react: "19.0.0" } })

  const resolveFoo = (probe: ReturnType<typeof probeOf>) =>
    createResolver({
      ts,
      host: probe.host,
      paths: probe.paths,
      tsconfig: probe.tsconfig,
      candidateSuffixes: probe.candidateSuffixes,
    }).resolveModule(`${ROOT}/src/App.tsx`, "./Foo")

  const nativeFiles = { "tsconfig.json": TSCONFIG, "src/App.tsx": PAGE }

  it("leaves web candidate suffixes empty", () => {
    const probe = probeOf({ ...nativeFiles, "package.json": WEB_PACKAGE })
    expect(probe.candidateSuffixes).toEqual([])
  })

  it("resolves a base-less variant file in a React Native project", () => {
    const probe = probeOf({
      ...nativeFiles,
      "package.json": NATIVE_PACKAGE,
      "src/Foo.ios.tsx": PAGE,
      "src/Foo.android.tsx": PAGE,
    })
    expect(probe.candidateSuffixes).toEqual(expect.arrayContaining([...DEFAULT_CANDIDATE_SUFFIXES]))
    expect(resolveFoo(probe)).toBe(`${ROOT}/src/Foo.ios.tsx`)
  })

  it("resolves the base first when a project has both base and variants", () => {
    const probe = probeOf({
      ...nativeFiles,
      "package.json": NATIVE_PACKAGE,
      "src/Foo.tsx": PAGE,
      "src/Foo.ios.tsx": PAGE,
    })
    expect(resolveFoo(probe)).toBe(`${ROOT}/src/Foo.tsx`)
  })

  it("honours tsconfig moduleSuffixes order outside React Native", () => {
    const probe = probeOf({
      "tsconfig.json": JSON.stringify({ compilerOptions: { moduleSuffixes: [".native", ""] }, include: ["src"] }),
      "package.json": WEB_PACKAGE,
      "src/App.tsx": PAGE,
      "src/Foo.tsx": PAGE,
      "src/Foo.native.tsx": PAGE,
    })
    expect(resolveFoo(probe)).toBe(`${ROOT}/src/Foo.native.tsx`)
  })
})
