import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join, sep } from "node:path"
import { fileURLToPath } from "node:url"
import { build } from "vite"

export const ASSETS_DIR = new URL("../src/emit/assets/", import.meta.url)

export const GENERATED_MODULE = new URL("generated.ts", ASSETS_DIR)

export const REPORT_UI_CONFIG = new URL("../report-ui/vite.config.ts", import.meta.url)

export const GENERATE_COMMAND = "pnpm assets"

export const IF_MISSING_FLAG = "--if-missing"

const BUILT_TEMPLATE_FILE = "index.html"

const BUILD_DIR_PREFIX = "appgraph-report-ui-"

export type InputTree = { readonly root: string; readonly ignored: readonly RegExp[] }

export type TemplateSources = {
  readonly module: string
  readonly trees: readonly InputTree[]
  readonly files: readonly string[]
}

export const REPORT_UI_IGNORED = [/^dist(\/|$)/, /^test(\/|$)/, /\.test\.tsx?$/] as const

const EMIT_INPUTS = ["i18n-runtime.ts", "html-util.ts", "strings.ts", "report-payload.ts"] as const

const fromRepo = (relative: string): string => fileURLToPath(new URL(`../${relative}`, import.meta.url))

export const DEFAULT_TEMPLATE_SOURCES: TemplateSources = {
  module: fileURLToPath(GENERATED_MODULE),
  trees: [{ root: fromRepo("report-ui/"), ignored: REPORT_UI_IGNORED }],
  files: EMIT_INPUTS.map((file) => fromRepo(`src/emit/${file}`)),
}

export const renderAssetsModule = (template: string): string =>
  [
    `// @generated by \`${GENERATE_COMMAND}\` from report-ui/ — do not edit by hand.`,
    "// The HTML emitter must not read this file at runtime: the published package ships dist/ only.",
    "",
    `export const REPORT_TEMPLATE = ${JSON.stringify(template)}`,
    "",
  ].join("\n")

const TEMPLATE_PREFIX = "export const REPORT_TEMPLATE = "

export const extractTemplate = (moduleText: string): string | null => {
  const line = moduleText.split("\n").find((candidate) => candidate.startsWith(TEMPLATE_PREFIX))
  if (line === undefined) return null
  const value: unknown = JSON.parse(line.slice(TEMPLATE_PREFIX.length))
  return typeof value === "string" ? value : null
}

const toPosix = (relative: string): string => relative.split(sep).join("/")

const isIgnored = (relative: string, ignored: readonly RegExp[]): boolean =>
  ignored.some((pattern) => pattern.test(relative))

const isFile = (file: string): boolean => statSync(file).isFile()

export const listTreeFiles = ({ root, ignored }: InputTree): string[] =>
  readdirSync(root, { recursive: true, encoding: "utf8" })
    .filter((relative) => !isIgnored(toPosix(relative), ignored))
    .map((relative) => join(root, relative))
    .filter(isFile)

const mtimeOf = (file: string): number => statSync(file).mtimeMs

export const newestMtime = (files: readonly string[]): number =>
  files.reduce((newest, file) => Math.max(newest, mtimeOf(file)), 0)

const moduleTemplate = (module: string): string | null =>
  existsSync(module) ? extractTemplate(readFileSync(module, "utf8")) : null

const templateInputs = ({ trees, files }: TemplateSources): string[] => [...trees.flatMap(listTreeFiles), ...files]

export const isTemplateStale = (sources: TemplateSources = DEFAULT_TEMPLATE_SOURCES): boolean => {
  if (moduleTemplate(sources.module) === null) return true
  return newestMtime(templateInputs(sources)) > mtimeOf(sources.module)
}

export const writeFileAtomic = (file: string, text: string): void => {
  mkdirSync(dirname(file), { recursive: true })
  const temporary = `${file}.${process.pid}.tmp`
  writeFileSync(temporary, text)
  renameSync(temporary, file)
}

const writeModule = (template: string): void => {
  const text = renderAssetsModule(template)
  writeFileAtomic(fileURLToPath(GENERATED_MODULE), text)
  process.stdout.write(`wrote ${fileURLToPath(GENERATED_MODULE)} (${text.length} bytes)\n`)
}

export const buildReportUi = async (outDir: string): Promise<void> => {
  await build({ configFile: fileURLToPath(REPORT_UI_CONFIG), logLevel: "warn", build: { outDir, emptyOutDir: true } })
}

const buildTemplate = async (): Promise<string> => {
  const outDir = mkdtempSync(join(tmpdir(), BUILD_DIR_PREFIX))
  try {
    await buildReportUi(outDir)
    return readFileSync(join(outDir, BUILT_TEMPLATE_FILE), "utf8")
  } finally {
    rmSync(outDir, { recursive: true, force: true })
  }
}

export const generateAssets = async (): Promise<void> => {
  writeModule(await buildTemplate())
}

const refreshModule = (template: string): void => {
  if (renderAssetsModule(template) === readFileSync(GENERATED_MODULE, "utf8")) return
  writeModule(template)
}

export const ensureTemplate = async (): Promise<void> => {
  const template = moduleTemplate(fileURLToPath(GENERATED_MODULE))
  if (template === null || isTemplateStale()) return generateAssets()
  refreshModule(template)
}

const main = async (): Promise<void> => {
  if (process.argv.includes(IF_MISSING_FLAG)) return ensureTemplate()
  return generateAssets()
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) await main()
