import type { Params } from "./i18n-runtime.js"
import { interpolate } from "./i18n-runtime.js"

export type Locale = "en" | "pl"

export const DEFAULT_LOCALE: Locale = "en"

const en = {
  headerTitle: "{{appName}} — screen & component map",
  countScreens: "screens",
  countRedirects: "redirects",
  countComponents: "components",
  countRenderEdges: "render edges",
  countNavEdges: "nav edges",
  countEndpoints: "endpoints",
  countDepth: "depth",
  countDeadLinks: "dead links",
  countApiRoutes: "API routes",

  tabScreens: "Screens",
  tabGraph: "Navigation map",
  tabMenu: "Menu",
  tabComponents: "Components",
  tabFindings: "Findings",

  screenDetailEmpty: "Select a screen.",
  screenFilterEmpty: "No screens match “{{query}}”",
  filterClear: "Clear filter",
  screenListApiGroup: "API routes",
  badgeAuthProtected: "auth",
  badgeAuthPublic: "public",
  badgeDevOnly: "dev only",
  badgeFlag: "flag: {{flag}}",
  badgeRedirect: "→ {{target}}",
  badgeUnaddressable: "not addressable",
  routeNameLabel: "Route name",

  sectionRenderTree: "Render tree",
  sectionOutgoingNav: "Transitions from this screen",
  sectionShell: "Shell (layout)",
  sectionAncestors: "Ancestor chain",
  sectionEndpoints: "API endpoints",
  sectionStores: "Stores",
  sectionQueryKeys: "React Query keys",
  sectionI18n: "i18n namespaces",
  sectionFeatureGates: "Feature gates (getConfiguration / featureFlag)",
  sectionFormSchemas: "Forms — schemas",
  sectionFormFields: "Forms — fields",
  sectionTestIds: "data-testid (agent selectors)",
  sectionMessages: "Message types (extension messaging)",
  sectionExtraChannel: "{{channel}} (plugin channel)",
  sectionParams: "URL parameters",
  sectionReach:
    "{{count}} file reachable from this screen (render + hooks/services).|{{count}} files reachable from this screen (render + hooks/services).",
  sectionActivation: "Activation",
  sectionRedirect: "Redirect",
  sectionReachTitle: "Reach",

  emptyGeneric: "none",
  emptyNav: "no outgoing transitions",
  emptyEndpoints: "no HTTP/RPC calls detected",
  emptyShell: "no shell (screen rendered without a layout)",
  emptyShellLinks: "no links in shell",
  emptyAncestors: "no wrapping layouts/guards",

  shellLinksIntro:
    "Links available from every screen with this layout (menu, account, notifications):",
  shellTreeSummary: "Shell tree",
  ancestorSplice: "splice: {{splice}}",
  ancestorRole: "role: {{role}}",

  treeRepeatNote: "already shown above",
  treeTruncatedNote: "… truncated (--depth)",
  treeCondAlways: "sometimes when {{conditions}}",
  treeCondOnly: "only when {{conditions}}",
  treeRepeatedLabel: "list",
  treeRepeatedTitle: "rendered inside .map()",
  treeGuardLabel: "null when {{guard}}",
  treeViaLazyLabel: "lazy",
  treeViaLazyTitle: "loaded on demand: lazy(), dynamic(), loadable(), defineAsyncComponent() or import()",
  treeViaReferenceLabel: "by reference",
  treeViaReferenceTitle: "referenced as a value, not rendered as a tag; renders only if selected at runtime",
  treeViaSelectorLabel: "selector",
  treeViaSelectorTitle: "matched by its Angular selector among the components the template's NgModule or standalone imports put in scope",
  treeViaSelectorGlobalLabel: "selector (global)",
  treeViaSelectorGlobalTitle: "matched by its Angular selector across the whole project, because no NgModule or standalone imports scope this template",

  activationKindUrl: "URL",
  activationKindState: "State-activated",
  activationKindHost: "Host",
  activationKindMessage: "Message",
  activationKindIntercept: "Intercepted",
  activationKindRoute: "Route name",
  activationStateDetail: "shown when {{expr}}",
  activationHostDetail: "matches host pattern {{pattern}}",
  activationMessageDetail: "triggered by message type {{messageType}}",
  activationInterceptDetail: "intercepted from {{from}}",
  activationUrlDetail: "URL template {{template}}",
  activationRouteDetail: "{{name}} in {{navigator}}",
  activationRouteNameDetail: "route name {{name}}",

  legendNode: "Screen (size = number of links)",
  legendNodeAuth: "Requires auth",
  legendAuthUnknown: "Auth status unknown",
  legendOutgoing: "Outgoing link: arrow points away from the screen (on hover or focus)",
  legendIncoming: "Incoming link: arrow points into the screen (on hover or focus)",
  legendEdge: "navigate() / <Link> detected in the screen's code",
  legendDynamic: "Target built dynamically (template literal)",
  legendLayout:
    "Columns group screens by first URL segment. Hover or focus a screen to trace its links; use the arrow keys to move between screens. Drag to pan; zoom with the Zoom in, Zoom out and Fit to view buttons or Ctrl/⌘ + wheel.",
  legendClick: "Click a screen to open its detail.",
  graphExcludedNote: "API routes, state-activated and other non-URL screens are not shown on this map.",
  graphZoomIn: "Zoom in",
  graphZoomOut: "Zoom out",
  graphZoomFit: "Fit to view",
  graphEmpty: "No screens with a URL to plot.",

  menuIntro: "Main menu read from {{source}} — available from every screen in shell(s): {{shells}}.",
  menuShellsUnknown: "not determined",
  menuColTitle: "Title",
  menuColI18nKey: "i18n key",
  menuColPath: "Path",
  menuColFlag: "Feature flag",
  menuColParent: "Parent group",
  menuColGroup: "Group",
  menuGroupAll: "All groups",
  menuGroupFilterLabel: "Menu group",
  menuMissingInRouter: "(missing from router)",
  navViaRedirect: "via redirect {{from}} → {{to}}",
  navViaRedirectWhen: "via redirect {{from}} → {{to}} (when {{condition}})",
  navViaRedirectAlternatives: "via redirect {{from}} → {{targets}}",
  navRedirectAlternative: "{{to}} (when {{condition}})",
  menuEmpty: "No menu entries.",

  componentKindAll: "All kinds",
  componentKindLabel: "Filter by kind",
  colComponent: "Component / route",
  colKind: "Kind",
  colFile: "File",
  colRenders: "Renders",
  colEndpoints: "Endpoints",
  colMutations: "Mutations",
  colStores: "Stores",

  findingsDeadLinksTitle: "Dead navigation links",
  findingsDeadLinksIntro: "These menu/nav entries point at a URL no screen serves.",
  findingsDeadLinksEmpty: "No dead links detected.",
  deadLinkColPath: "Path",
  deadLinkColLabel: "Label",
  deadLinkColSource: "Source",
  deadLinkColLocation: "File:line",

  findingsOrphansTitle: "Orphan screens",
  findingsOrphansIntro:
    "Addressable screens with no inbound navigation edge. Often legitimate (deep links) — informational only.",
  findingsOrphansEmpty: "No orphan screens detected.",

  findingsConfidenceTitle: "Data confidence",
  findingsConfidenceEmpty: "No confidence data.",
  confidenceColSection: "Section",
  confidenceColCount: "Count",
  confidenceColDependency: "Enabling dependency",
  confidenceColStatus: "Status",
  confidenceSuspectFlag: "unexpectedly empty",
  confidenceStatusOk: "ok",
  confidenceStatusPartial: "partial",
  confidenceStatusEmptyExpected: "empty (expected)",
  confidenceStatusEmptyUnexpected: "empty (unexpected)",

  findingsDiagnosticsTitle: "Diagnostics",
  diagnosticsEmpty: "No diagnostics.",
  diagnosticsSeverityEmpty: "No diagnostics at this severity.",
  diagnosticColSeverity: "Severity",
  diagnosticColCode: "Code",
  diagnosticColMessage: "Message",
  diagnosticColPlugin: "Plugin",
  diagnosticSeverityAll: "All severities",
  severityError: "Errors",
  severityWarning: "Warnings",
  severityInfo: "Info",
  severityErrorOne: "Error",
  severityWarningOne: "Warning",
  severityInfoOne: "Info",
  diagnosticPlugin: "plugin: {{plugin}}",
  diagnosticLocation: "{{file}}:{{line}}",

  limitationsTitle: "Static-analysis boundaries",
  dash: "—",
  badgeAuthUnknown: "auth unknown",
  screenFilterLabel: "Find a screen",
  screenFilterExample: "e.g. login, /billing, settings",
  graphFilterLabel: "Highlight screens on the map",
  graphFilterExample: "e.g. users",
  menuFilterLabel: "Find a menu entry",
  menuFilterExample: "e.g. settings, /account",
  componentFilterLabel: "Find a component",
  componentFilterExample: "e.g. Header, src/ui/forms",
  findingsFilterLabel: "Filter findings",
  findingsFilterExample: "e.g. /old-page, warning",
  deadLinksFilterLabel: "Find a dead link",
  deadLinksFilterExample: "e.g. /old-page, nav.ts",
  confidenceFilterLabel: "Find a data section",
  confidenceFilterExample: "e.g. routes, partial",
  diagnosticsFilterLabel: "Find a diagnostic",
  diagnosticsFilterExample: "e.g. warning, plugin name",
  infoTipLabel: "What does “{{term}}” mean?",
  helpScreens: "A screen is one page or view a user can open, such as a login page or a dashboard.",
  helpApiRoutes: "Routes that answer requests from other programs instead of showing a page.",
  helpRenderTree: "The components a screen draws, shown as a tree: each component sits under the one that uses it.",
  helpAncestors: "The layouts and access checks that wrap this screen, from the outermost one inward.",
  helpSplice: "Where the screen is placed inside its wrapper: as its children, in an outlet, or at a spot in the code.",
  helpShell:
    "The shared frame around a screen, such as the top bar and side menu. Its links work from every screen that uses it.",
  helpReach: "How many source files this screen depends on, directly or through other files it uses.",
  helpActivation:
    "What makes a screen appear: a URL, a state value, a host name, a message or a route name. Route name: a native screen reached by its name, not by a URL.",
  helpRenderEdges: "Each “component A draws component B” link. More of them means a bigger, more nested interface.",
  helpNavEdges:
    "Each place where one screen can send the user to another, for example a link or a redirect in code.",
  helpDepth: "The deepest level of components drawn inside one another. Deeper trees are harder to follow.",
  helpEndpoints: "Server addresses the code calls to get or send data.",
  helpRedirects: "URLs that automatically send the visitor to a different URL.",
  helpComponents: "Reusable building blocks of the interface, such as buttons, forms and whole pages.",
  helpDeadLinks:
    "Menu or navigation entries that lead to an address no screen handles. Users would see an error.",
  helpOrphans:
    "Screens with an address but no link leading to them. Often fine, for example pages opened from emails.",
  helpConfidence:
    "How much to trust each part of this report. “Empty” can mean nothing was found or the tool could not look.",
  helpKind: "The type of a component, for example page, layout or widget, as detected from the code.",
  helpTransport: "How a call is sent: a normal web request (HTTP) or a remote procedure call (RPC).",
  helpI18n: "Groups of translated texts this screen loads. Useful to see which languages files it needs.",
  helpQueryKeys: "Names under which fetched data is cached by React Query. Same name means shared data.",
  helpStores: "Shared data containers that many components can read and change.",
  helpFeatureGates: "Switches that turn a feature on or off without a new release.",
  helpFormSchemas: "Rules that describe what a form accepts, such as required fields and allowed values.",
  helpFormFields: "The inputs a user fills in on this screen's forms.",
  helpTestIds: "Labels added to elements so automated tests and agents can find them reliably.",
  helpMessages: "Messages sent between parts of a browser extension, such as the page and the background script.",
  helpCondOnly: "This component is drawn only when the condition is true.",
  helpCondSometimes: "This component is drawn always in one place and also under extra conditions elsewhere.",
  helpGuard: "A null guard: the component draws nothing when this check passes, for example when data is missing.",
  helpRepeated: "This component is drawn once per item of a list, so it can appear many times.",
  helpAuth: "Whether a login is needed to open the screen. “Unknown” means the tool could not tell.",
  glossaryOpen: "Glossary",
  glossaryTitle: "Glossary of terms",
  glossaryIntro: "Short explanations of the technical terms used in this report.",
  glossaryTermSplice: "splice",
  glossaryTermTransport: "transport",
  glossaryTermCondOnly: "only when…",
  glossaryTermCondSometimes: "sometimes when…",
  glossaryTermGuard: "null when…",
  moreStatsLabel: "More stats",
  moreStatsTitle: "All counts",
  generatedAtLabel: "Generated",
  themeMenuLabel: "Theme",
  themeLight: "Light",
  themeDark: "Dark",
  themeSystem: "System",
  paletteOpen: "Open command palette",
  palettePlaceholder: "Type a command or screen name…",
  paletteEmpty: "Nothing found.",
  paletteKeepTyping: "Keep typing to narrow the list",
  paletteGroupTabs: "Go to tab",
  paletteGroupScreens: "Screens",
  paletteGroupActions: "Actions",
  shortcutsOpen: "Keyboard shortcuts",
  shortcutsTitle: "Keyboard shortcuts",
  shortcutsIntro: "Shortcuts are paused while you type in a text field, except Esc.",
  shortcutsGroupNavigation: "Navigation",
  shortcutsGroupSearch: "Search and commands",
  shortcutsGroupList: "List",
  shortcutThen: "then",
  shortcutFocusSearch: "Focus the search field of this tab",
  shortcutPalette: "Open command palette",
  shortcutGoScreens: "Go to Screens",
  shortcutGoGraph: "Go to Navigation map",
  shortcutGoMenu: "Go to Menu",
  shortcutGoComponents: "Go to Components",
  shortcutGoFindings: "Go to Findings",
  shortcutNextScreen: "Next screen in the list",
  shortcutPrevScreen: "Previous screen in the list",
  shortcutClear: "Clear the search or close the dialog",
  shortcutHelp: "Show this list",
  copyLabel: "Copy {{what}}",
  copied: "Copied",
  copyFailed: "Could not copy. Select the text and copy it by hand.",
  hashUnknownScreen: "Screen “{{id}}” is not in this report.",
  componentsFilterEmpty: "No components match “{{query}}”.",
  componentsEmpty: "No components found in this app.",
  graphFilterEmpty: "No screens on the map match “{{query}}”.",
  graphFilterMatches: "{{count}} matching screen|{{count}} matching screens",
  menuFilterEmpty: "No menu entries match “{{query}}”.",
  findingsFilterEmpty: "No findings match “{{query}}”.",
  findingsFilterMatches: "{{count}} finding|{{count}} findings",
  screenListCount: "{{count}} screen|{{count}} screens",
  emptyResultTitle: "No screens were found",
  emptyResultBody: "{{reason}}",
  emptyResultHint: "The report was written on purpose with no data. Check the tool's diagnostics in Findings.",
  tabsLabel: "Report sections",
  tabScreensDescription: "Every screen with its components, data calls and links",
  tabGraphDescription: "How screens link to each other",
  tabMenuDescription: "Entries of the app's main menu",
  tabComponentsDescription: "All components found in the code",
  tabFindingsDescription: "Dead links, orphan screens, data confidence and diagnostics",
  tableRowCount: "Rows: {{shown}} of {{total}}",
  sortAscending: "Sort by {{column}}, ascending",
  sortDescending: "Sort by {{column}}, descending",
  sortNone: "Sort by {{column}}",
  screenListLabel: "Screens",
  graphSvgLabel: "Navigation map of screens",
  graphNodeLabel: "{{title}}, links: {{count}}",
  graphSummaryScreens: "{{count}} screen|{{count}} screens",
  graphSummaryLinks: "{{count}} distinct link|{{count}} distinct links",
  statScreensPlural: "{{count}} screen|{{count}} screens",
  statComponentsPlural: "{{count}} component|{{count}} components",
  statEndpointsPlural: "{{count}} endpoint|{{count}} endpoints",
  statDeadLinksPlural: "{{count}} dead link|{{count}} dead links",
  statApiRoutesPlural: "{{count}} API route|{{count}} API routes",
  statRedirectsPlural: "{{count}} redirect|{{count}} redirects",
  statRenderEdgesPlural: "{{count}} render edge|{{count}} render edges",
  statNavEdgesPlural: "{{count}} nav edge|{{count}} nav edges",
  navChipSourcesPlural: "{{count}} source|{{count}} sources",
  dialogClose: "Close",
  paletteResults: "Results",
  notificationsRegion: "Notifications",
  limitationsLink: "Limitations",
  spliceChildren: "children",
  spliceOutlet: "outlet <{{tag}}>",
  spliceAt: "at {{export}}#{{path}}",
  skipToContent: "Skip to content",
  showEmptySections: "Show empty sections ({{count}})",
  screenSelectionHidden: "The selected screen “{{label}}” is hidden by the filter.",
  endpointFilterLabel: "Find an endpoint",
  endpointFilterExample: "e.g. /api/users, POST",
  endpointFilterEmpty: "No endpoints match “{{query}}”.",
  colMethod: "Method",
  colUrl: "URL",
  colClient: "Client",
} as const

export type StringKey = keyof typeof en

export const PLURAL_KEYS = [
  "graphFilterMatches",
  "findingsFilterMatches",
  "screenListCount",
  "graphSummaryScreens",
  "graphSummaryLinks",
  "sectionReach",
  "statScreensPlural",
  "statComponentsPlural",
  "statEndpointsPlural",
  "statDeadLinksPlural",
  "statApiRoutesPlural",
  "statRedirectsPlural",
  "statRenderEdgesPlural",
  "statNavEdgesPlural",
  "navChipSourcesPlural",
] as const satisfies readonly StringKey[]

const pl: Record<StringKey, string> = {
  headerTitle: "{{appName}} — mapa ścieżek i komponentów",
  countScreens: "ekrany",
  countRedirects: "przekierowania",
  countComponents: "komponenty",
  countRenderEdges: "krawędzie render",
  countNavEdges: "krawędzie nawigacji",
  countEndpoints: "endpointy",
  countDepth: "głębokość",
  countDeadLinks: "martwe linki",
  countApiRoutes: "trasy API",

  tabScreens: "Ekrany",
  tabGraph: "Mapa nawigacji",
  tabMenu: "Menu",
  tabComponents: "Komponenty",
  tabFindings: "Ustalenia",

  screenDetailEmpty: "Wybierz ekran.",
  screenFilterEmpty: "Żaden ekran nie pasuje do „{{query}}”",
  filterClear: "Wyczyść filtr",
  screenListApiGroup: "Trasy API",
  badgeAuthProtected: "auth",
  badgeAuthPublic: "publiczny",
  badgeDevOnly: "tylko dev",
  badgeFlag: "flaga: {{flag}}",
  badgeRedirect: "→ {{target}}",
  badgeUnaddressable: "brak adresu",
  routeNameLabel: "Nazwa trasy",

  sectionRenderTree: "Drzewo renderowania",
  sectionOutgoingNav: "Przejścia z tego ekranu",
  sectionShell: "Powłoka (layout)",
  sectionAncestors: "Łańcuch przodków",
  sectionEndpoints: "Endpointy API",
  sectionStores: "Store'y",
  sectionQueryKeys: "Klucze react-query",
  sectionI18n: "Namespace'y i18n",
  sectionFeatureGates: "Bramki funkcji (getConfiguration / featureFlag)",
  sectionFormSchemas: "Formularze — schematy",
  sectionFormFields: "Formularze — pola",
  sectionTestIds: "data-testid (selektory dla agenta)",
  sectionMessages: "Typy wiadomości (komunikacja rozszerzenia)",
  sectionExtraChannel: "{{channel}} (kanał wtyczki)",
  sectionParams: "Parametry URL",
  sectionReach:
    "{{count}} plik osiągalny z tego ekranu (render + hooki/serwisy).|{{count}} pliki osiągalne z tego ekranu (render + hooki/serwisy).|{{count}} plików osiągalnych z tego ekranu (render + hooki/serwisy).",
  sectionActivation: "Aktywacja",
  sectionRedirect: "Przekierowanie",
  sectionReachTitle: "Zasięg",

  emptyGeneric: "brak",
  emptyNav: "brak wychodzących przejść",
  emptyEndpoints: "brak wykrytych wywołań HTTP/RPC",
  emptyShell: "brak powłoki (ekran renderowany bez layoutu)",
  emptyShellLinks: "brak linków w powłoce",
  emptyAncestors: "brak otaczających layoutów/strażników",

  shellLinksIntro: "Linki dostępne z każdego ekranu z tym layoutem (menu, konto, powiadomienia):",
  shellTreeSummary: "Drzewo powłoki",
  ancestorSplice: "wstawienie: {{splice}}",
  ancestorRole: "rola: {{role}}",

  treeRepeatNote: "już wyżej",
  treeTruncatedNote: "… obcięte (--depth)",
  treeCondAlways: "czasem gdy {{conditions}}",
  treeCondOnly: "tylko gdy {{conditions}}",
  treeRepeatedLabel: "lista",
  treeRepeatedTitle: "renderowane w .map()",
  treeGuardLabel: "null gdy {{guard}}",
  treeViaLazyLabel: "lazy",
  treeViaLazyTitle: "ładowany na żądanie: lazy(), dynamic(), loadable(), defineAsyncComponent() lub import()",
  treeViaReferenceLabel: "przez referencję",
  treeViaReferenceTitle: "użyty jako wartość, nie wyrenderowany jako tag; renderuje się tylko, gdy zostanie wybrany w czasie działania",
  treeViaSelectorLabel: "selektor",
  treeViaSelectorTitle: "dopasowany po selektorze Angulara spośród komponentów, które NgModule lub importy standalone szablonu udostępniają w jego zakresie",
  treeViaSelectorGlobalLabel: "selektor (globalnie)",
  treeViaSelectorGlobalTitle: "dopasowany po selektorze Angulara w całym projekcie, bo żaden NgModule ani importy standalone nie określają zakresu tego szablonu",

  activationKindUrl: "URL",
  activationKindState: "Aktywowany stanem",
  activationKindHost: "Host",
  activationKindMessage: "Wiadomość",
  activationKindIntercept: "Przechwycony",
  activationKindRoute: "Nazwa trasy",
  activationStateDetail: "widoczny gdy {{expr}}",
  activationHostDetail: "pasuje do wzorca hosta {{pattern}}",
  activationMessageDetail: "wywoływany typem wiadomości {{messageType}}",
  activationInterceptDetail: "przechwycony z {{from}}",
  activationUrlDetail: "szablon URL {{template}}",
  activationRouteDetail: "{{name}} w {{navigator}}",
  activationRouteNameDetail: "nazwa trasy {{name}}",

  legendNode: "Ekran (rozmiar = liczba połączeń)",
  legendNodeAuth: "Wymaga logowania",
  legendAuthUnknown: "Logowanie nieustalone",
  legendOutgoing: "Połączenie wychodzące: strzałka wychodzi z ekranu (po najechaniu lub fokusie)",
  legendIncoming: "Połączenie przychodzące: strzałka wchodzi do ekranu (po najechaniu lub fokusie)",
  legendEdge: "navigate() / <Link> wykryte w kodzie ekranu",
  legendDynamic: "Cel budowany dynamicznie (template literal)",
  legendLayout:
    "Kolumny grupują ekrany po pierwszym segmencie URL. Najedź lub ustaw fokus na ekranie, aby prześledzić jego połączenia; strzałkami przechodzisz między ekranami. Przeciągnij, aby przesunąć; powiększaj przyciskami Przybliż, Oddal i Dopasuj do widoku albo Ctrl/⌘ + kółkiem.",
  legendClick: "Kliknij ekran, aby otworzyć jego szczegóły.",
  graphExcludedNote: "Trasy API, ekrany aktywowane stanem i inne bez URL nie są pokazane na tej mapie.",
  graphZoomIn: "Przybliż",
  graphZoomOut: "Oddal",
  graphZoomFit: "Dopasuj do widoku",
  graphEmpty: "Brak ekranów z URL do narysowania.",

  menuIntro: "Menu główne czytane z {{source}} — dostępne z każdego ekranu w powłoce: {{shells}}.",
  menuShellsUnknown: "nie ustalono",
  menuColTitle: "Tytuł",
  menuColI18nKey: "Klucz i18n",
  menuColPath: "Ścieżka",
  menuColFlag: "Feature flag",
  menuColParent: "Grupa nadrzędna",
  menuColGroup: "Grupa",
  menuGroupAll: "Wszystkie grupy",
  menuGroupFilterLabel: "Grupa menu",
  menuMissingInRouter: "(brak w routerze)",
  navViaRedirect: "przez przekierowanie {{from}} → {{to}}",
  navViaRedirectWhen: "przez przekierowanie {{from}} → {{to}} (gdy {{condition}})",
  navViaRedirectAlternatives: "przez przekierowanie {{from}} → {{targets}}",
  navRedirectAlternative: "{{to}} (gdy {{condition}})",
  menuEmpty: "Brak pozycji menu.",

  componentKindAll: "Wszystkie rodzaje",
  componentKindLabel: "Filtruj po rodzaju",
  colComponent: "Komponent / trasa",
  colKind: "Rodzaj",
  colFile: "Plik",
  colRenders: "Renderuje",
  colEndpoints: "Endpointy",
  colMutations: "Mutacje",
  colStores: "Store'y",

  findingsDeadLinksTitle: "Martwe linki nawigacyjne",
  findingsDeadLinksIntro: "Te pozycje menu/nawigacji wskazują na URL, którego nie obsługuje żaden ekran.",
  findingsDeadLinksEmpty: "Nie wykryto martwych linków.",
  deadLinkColPath: "Ścieżka",
  deadLinkColLabel: "Etykieta",
  deadLinkColSource: "Źródło",
  deadLinkColLocation: "Plik:linia",

  findingsOrphansTitle: "Ekrany sieroty",
  findingsOrphansIntro:
    "Adresowalne ekrany bez żadnej wchodzącej krawędzi nawigacji. Często uzasadnione (deep linki) — tylko informacyjnie.",
  findingsOrphansEmpty: "Nie wykryto ekranów sierot.",

  findingsConfidenceTitle: "Pewność danych",
  findingsConfidenceEmpty: "Brak danych o pewności.",
  confidenceColSection: "Sekcja",
  confidenceColCount: "Liczba",
  confidenceColDependency: "Zależność włączająca",
  confidenceColStatus: "Status",
  confidenceSuspectFlag: "nieoczekiwanie pusta",
  confidenceStatusOk: "ok",
  confidenceStatusPartial: "częściowo",
  confidenceStatusEmptyExpected: "pusta (oczekiwane)",
  confidenceStatusEmptyUnexpected: "pusta (nieoczekiwane)",

  findingsDiagnosticsTitle: "Diagnostyka",
  diagnosticsEmpty: "Brak diagnostyki.",
  diagnosticsSeverityEmpty: "Brak diagnostyki o tym poziomie.",
  diagnosticColSeverity: "Poziom",
  diagnosticColCode: "Kod",
  diagnosticColMessage: "Komunikat",
  diagnosticColPlugin: "Plugin",
  diagnosticSeverityAll: "Wszystkie poziomy",
  severityError: "Błędy",
  severityWarning: "Ostrzeżenia",
  severityInfo: "Informacje",
  severityErrorOne: "Błąd",
  severityWarningOne: "Ostrzeżenie",
  severityInfoOne: "Informacja",
  diagnosticPlugin: "plugin: {{plugin}}",
  diagnosticLocation: "{{file}}:{{line}}",

  limitationsTitle: "Granice analizy statycznej",
  dash: "—",
  badgeAuthUnknown: "auth nieustalone",
  screenFilterLabel: "Znajdź ekran",
  screenFilterExample: "np. login, /billing, ustawienia",
  graphFilterLabel: "Wyróżnij ekrany na mapie",
  graphFilterExample: "np. użytkownicy",
  menuFilterLabel: "Znajdź pozycję menu",
  menuFilterExample: "np. ustawienia, /konto",
  componentFilterLabel: "Znajdź komponent",
  componentFilterExample: "np. Header, src/ui/forms",
  findingsFilterLabel: "Filtruj ustalenia",
  findingsFilterExample: "np. /stara-strona, ostrzeżenie",
  deadLinksFilterLabel: "Znajdź martwy link",
  deadLinksFilterExample: "np. /stara-strona, nav.ts",
  confidenceFilterLabel: "Znajdź sekcję danych",
  confidenceFilterExample: "np. trasy, częściowo",
  diagnosticsFilterLabel: "Znajdź diagnostykę",
  diagnosticsFilterExample: "np. ostrzeżenie, nazwa pluginu",
  infoTipLabel: "Co oznacza „{{term}}”?",
  helpScreens:
    "Ekran to jedna strona lub widok, który użytkownik może otworzyć, na przykład logowanie albo pulpit.",
  helpApiRoutes: "Trasy, które odpowiadają na żądania innych programów, zamiast pokazywać stronę.",
  helpRenderTree: "Komponenty, które rysuje ekran, w postaci drzewa: każdy leży pod komponentem, który go używa.",
  helpAncestors: "Layouty i kontrole dostępu, które otaczają ten ekran, od najbardziej zewnętrznego do wewnątrz.",
  helpSplice: "Miejsce ekranu w otaczającym go komponencie: jako jego dzieci, w „outlet” albo w konkretnym miejscu kodu.",
  helpShell:
    "Wspólna rama wokół ekranu, na przykład górny pasek i boczne menu. Jej linki działają na każdym ekranie, który jej używa.",
  helpReach: "Od ilu plików źródłowych zależy ten ekran, bezpośrednio lub przez inne używane pliki.",
  helpActivation:
    "Co powoduje pojawienie się ekranu: adres URL, wartość stanu, nazwa hosta, wiadomość albo nazwa trasy. Nazwa trasy: ekran natywny otwierany po nazwie, nie po adresie URL.",
  helpRenderEdges:
    "Każde powiązanie „komponent A rysuje komponent B”. Im więcej ich, tym większy i bardziej zagnieżdżony interfejs.",
  helpNavEdges:
    "Każde miejsce, z którego jeden ekran może przenieść użytkownika na inny, na przykład link lub przekierowanie w kodzie.",
  helpDepth: "Najgłębszy poziom komponentów zagnieżdżonych jeden w drugim. Głębsze drzewa trudniej śledzić.",
  helpEndpoints: "Adresy serwera, które kod wywołuje, aby pobrać lub wysłać dane.",
  helpRedirects: "Adresy URL, które automatycznie przenoszą odwiedzającego pod inny adres.",
  helpComponents: "Wielokrotnego użytku klocki interfejsu, takie jak przyciski, formularze i całe strony.",
  helpDeadLinks:
    "Pozycje menu lub nawigacji, które prowadzą pod adres nieobsługiwany przez żaden ekran. Użytkownik zobaczyłby błąd.",
  helpOrphans:
    "Ekrany z adresem, do których nie prowadzi żaden link. Często to w porządku, na przykład strony otwierane z maili.",
  helpConfidence:
    "Na ile ufać poszczególnym częściom raportu. „Pusta” może znaczyć, że nic nie znaleziono albo że narzędzie nie mogło zajrzeć.",
  helpKind: "Rodzaj komponentu, na przykład strona, layout lub widżet, wykryty na podstawie kodu.",
  helpTransport: "Sposób wysłania wywołania: zwykłe żądanie sieciowe (HTTP) albo zdalne wywołanie procedury (RPC).",
  helpI18n: "Grupy przetłumaczonych tekstów, które ładuje ten ekran. Pokazują, z których plików tłumaczeń korzysta.",
  helpQueryKeys:
    "Nazwy, pod którymi React Query zapisuje pobrane dane w pamięci podręcznej. Ta sama nazwa oznacza wspólne dane.",
  helpStores: "Wspólne magazyny danych, które wiele komponentów może czytać i zmieniać.",
  helpFeatureGates: "Przełączniki, które włączają lub wyłączają funkcję bez nowego wydania.",
  helpFormSchemas: "Reguły opisujące, co przyjmuje formularz, na przykład pola wymagane i dozwolone wartości.",
  helpFormFields: "Pola, które użytkownik wypełnia w formularzach tego ekranu.",
  helpTestIds: "Etykiety dodane do elementów, dzięki którym testy automatyczne i agenci mogą je niezawodnie znaleźć.",
  helpMessages: "Wiadomości wysyłane między częściami rozszerzenia przeglądarki, na przykład stroną i skryptem w tle.",
  helpCondOnly: "Ten komponent jest rysowany tylko wtedy, gdy warunek jest spełniony.",
  helpCondSometimes: "Ten komponent jest rysowany zawsze w jednym miejscu, a gdzie indziej także pod dodatkowymi warunkami.",
  helpGuard: "Strażnik null: komponent nic nie rysuje, gdy ten warunek zachodzi, na przykład gdy brakuje danych.",
  helpRepeated: "Ten komponent jest rysowany raz dla każdego elementu listy, więc może pojawić się wiele razy.",
  helpAuth: "Czy do otwarcia ekranu trzeba się zalogować. „Nieustalone” oznacza, że narzędzie nie potrafiło tego stwierdzić.",
  glossaryOpen: "Słowniczek",
  glossaryTitle: "Słowniczek pojęć",
  glossaryIntro: "Krótkie objaśnienia terminów technicznych użytych w tym raporcie.",
  glossaryTermSplice: "wstawienie",
  glossaryTermTransport: "transport",
  glossaryTermCondOnly: "tylko gdy…",
  glossaryTermCondSometimes: "czasem gdy…",
  glossaryTermGuard: "null gdy…",
  moreStatsLabel: "Więcej statystyk",
  moreStatsTitle: "Wszystkie liczby",
  generatedAtLabel: "Wygenerowano",
  themeMenuLabel: "Motyw",
  themeLight: "Jasny",
  themeDark: "Ciemny",
  themeSystem: "Systemowy",
  paletteOpen: "Otwórz paletę poleceń",
  palettePlaceholder: "Wpisz polecenie lub nazwę ekranu…",
  paletteEmpty: "Nic nie znaleziono.",
  paletteKeepTyping: "Pisz dalej, aby zawęzić listę",
  paletteGroupTabs: "Przejdź do zakładki",
  paletteGroupScreens: "Ekrany",
  paletteGroupActions: "Akcje",
  shortcutsOpen: "Skróty klawiszowe",
  shortcutsTitle: "Skróty klawiszowe",
  shortcutsIntro: "Skróty są wstrzymane podczas pisania w polu tekstowym, poza klawiszem Esc.",
  shortcutsGroupNavigation: "Nawigacja",
  shortcutsGroupSearch: "Wyszukiwanie i polecenia",
  shortcutsGroupList: "Lista",
  shortcutThen: "potem",
  shortcutFocusSearch: "Przejdź do pola wyszukiwania w tej zakładce",
  shortcutPalette: "Otwórz paletę poleceń",
  shortcutGoScreens: "Przejdź do Ekranów",
  shortcutGoGraph: "Przejdź do Mapy nawigacji",
  shortcutGoMenu: "Przejdź do Menu",
  shortcutGoComponents: "Przejdź do Komponentów",
  shortcutGoFindings: "Przejdź do Ustaleń",
  shortcutNextScreen: "Następny ekran na liście",
  shortcutPrevScreen: "Poprzedni ekran na liście",
  shortcutClear: "Wyczyść wyszukiwanie lub zamknij okno",
  shortcutHelp: "Pokaż tę listę",
  copyLabel: "Kopiuj {{what}}",
  copied: "Skopiowano",
  copyFailed: "Nie udało się skopiować. Zaznacz tekst i skopiuj go ręcznie.",
  hashUnknownScreen: "Ekranu „{{id}}” nie ma w tym raporcie.",
  componentsFilterEmpty: "Żaden komponent nie pasuje do „{{query}}”.",
  componentsEmpty: "Nie znaleziono komponentów w tej aplikacji.",
  graphFilterEmpty: "Żaden ekran na mapie nie pasuje do „{{query}}”.",
  graphFilterMatches: "{{count}} pasujący ekran|{{count}} pasujące ekrany|{{count}} pasujących ekranów",
  menuFilterEmpty: "Żadna pozycja menu nie pasuje do „{{query}}”.",
  findingsFilterEmpty: "Żadne ustalenie nie pasuje do „{{query}}”.",
  findingsFilterMatches: "{{count}} ustalenie|{{count}} ustalenia|{{count}} ustaleń",
  screenListCount: "{{count}} ekran|{{count}} ekrany|{{count}} ekranów",
  emptyResultTitle: "Nie znaleziono żadnych ekranów",
  emptyResultBody: "{{reason}}",
  emptyResultHint: "Raport zapisano celowo bez danych. Sprawdź diagnostykę narzędzia w Ustaleniach.",
  tabsLabel: "Sekcje raportu",
  tabScreensDescription: "Każdy ekran z komponentami, wywołaniami danych i linkami",
  tabGraphDescription: "Jak ekrany łączą się ze sobą",
  tabMenuDescription: "Pozycje głównego menu aplikacji",
  tabComponentsDescription: "Wszystkie komponenty znalezione w kodzie",
  tabFindingsDescription: "Martwe linki, ekrany sieroty, pewność danych i diagnostyka",
  tableRowCount: "Wiersze: {{shown}} z {{total}}",
  sortAscending: "Sortuj wg {{column}} rosnąco",
  sortDescending: "Sortuj wg {{column}} malejąco",
  sortNone: "Sortuj wg {{column}}",
  screenListLabel: "Ekrany",
  graphSvgLabel: "Mapa nawigacji ekranów",
  graphNodeLabel: "{{title}}, linki: {{count}}",
  graphSummaryScreens: "{{count}} ekran|{{count}} ekrany|{{count}} ekranów",
  graphSummaryLinks:
    "{{count}} unikalne połączenie|{{count}} unikalne połączenia|{{count}} unikalnych połączeń",
  statScreensPlural: "{{count}} ekran|{{count}} ekrany|{{count}} ekranów",
  statComponentsPlural: "{{count}} komponent|{{count}} komponenty|{{count}} komponentów",
  statEndpointsPlural: "{{count}} endpoint|{{count}} endpointy|{{count}} endpointów",
  statDeadLinksPlural: "{{count}} martwy link|{{count}} martwe linki|{{count}} martwych linków",
  statApiRoutesPlural: "{{count}} trasa API|{{count}} trasy API|{{count}} tras API",
  statRedirectsPlural: "{{count}} przekierowanie|{{count}} przekierowania|{{count}} przekierowań",
  statRenderEdgesPlural: "{{count}} krawędź render|{{count}} krawędzie render|{{count}} krawędzi render",
  statNavEdgesPlural: "{{count}} krawędź nawigacji|{{count}} krawędzie nawigacji|{{count}} krawędzi nawigacji",
  navChipSourcesPlural: "{{count}} źródło|{{count}} źródła|{{count}} źródeł",
  dialogClose: "Zamknij",
  paletteResults: "Wyniki",
  notificationsRegion: "Powiadomienia",
  limitationsLink: "Ograniczenia",
  spliceChildren: "dzieci",
  spliceOutlet: "outlet <{{tag}}>",
  spliceAt: "w {{export}}#{{path}}",
  skipToContent: "Przejdź do treści",
  showEmptySections: "Pokaż puste sekcje ({{count}})",
  screenSelectionHidden: "Wybrany ekran „{{label}}” jest ukryty przez filtr.",
  endpointFilterLabel: "Znajdź endpoint",
  endpointFilterExample: "np. /api/users, POST",
  endpointFilterEmpty: "Żaden endpoint nie pasuje do „{{query}}”.",
  colMethod: "Metoda",
  colUrl: "URL",
  colClient: "Klient",
}

const bundles: Record<Locale, Record<StringKey, string>> = { en, pl }

export const STRING_KEYS: readonly string[] = Object.keys(en)

export const stringTable = (locale: Locale): Readonly<Record<StringKey, string>> => ({ ...en, ...bundles[locale] })

export const t = (locale: Locale, key: StringKey, params?: Params): string => {
  const bundle = bundles[locale]
  const template = bundle[key]
  return interpolate(template, params)
}
